name: Build Android APK (Final Release)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Final Release APK
        run: ./gradlew assembleRelease

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: final-app-release
          path: app/build/outputs/apk/release/*.apk
